version: '2'

volumes:
  nextcloud:
  conf.d:
  vhost.d:
  html:

networks:
  proxy:

services:
  # Proxy
  web:
    image: nginx
    container_name: nextcloud_web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
      - ./configs/full-nextcloud.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextcloud
    networks:
      - proxy
    env_file:
      - env/nextcloud.env

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./configs/uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - proxy

  dockergen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    networks:
      - proxy
    volumes_from: 
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./templates:/etc/docker-gen/templates/
    depends_on:
      - nginx

  letsencrypt-companion:
      image: jrcs/letsencrypt-nginx-proxy-companion
      container_name: nginx-letsencrypt
      restart: always
      volumes:
        - ./certs:/etc/nginx/certs
        - conf.d:/etc/nginx/conf.d
        - vhost.d:/etc/nginx/vhost.d
        - html:/usr/share/nginx/html
        - /var/run/docker.sock:/var/run/docker.sock:ro
      networks:
        - proxy
      depends_on:
        - dockergen
      environment:
        - NGINX_PROXY_CONTAINER=nginx
        - NGINX_DOCKER_GEN_CONTAINER=dockergen
  
  # Nextcloud
  db:
    image: mariadb
    container_name: nextcloud-db
    restart: always
    volumes:
      - /mnt/other/mysql:/var/lib/mysql
    env_file:
      - env/db.env
    networks:
      - proxy

  nextcloud:  
    image: nextcloud:fpm
    container_name: nextcloud
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - /mnt/other/nextcloud:/var/www/html/data
    environment:
      - MYSQL_HOST=db
    env_file:
      - env/db.env
    depends_on:
      - db
    networks:
      - proxy

  # Emby
  emby:
    image: emby/embyserver:latest
    container_name: emby
    restart: always
    volumes:
      - /mnt/movies1:/mnt/movies1:ro
      - /mnt/movies2:/mnt/movies2:ro
      - /mnt/other/embyconfig:/config
      - /mnt/other:/mnt/other:ro
    networks:
      - proxy
    env_file:
      - env/emby.env 
    environment:
      - VIRTUAL_PORT=8096

